name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.20", "1.21", "1.22"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - run: go get -t -v ./...
      - run: go test -race -coverprofile=coverage.out -covermode=atomic
      - uses: codecov/codecov-action@v4